export enum Features {
  Auth = 'auth',
  User = 'user',
  Users = 'users',
  Organizations = 'organizations',
  WorkProjects = 'workProjects',
  WorkGroups = 'workGroups',
  GlobalSearch = 'globalSearch',
  WorkTickets = 'workTickets',
  WorkTasks = 'workTasks',
  Attachments = 'attachments',
  History = 'history',
  TaskBoard = 'taskBoard',
  Dictionary = 'dictionary',
}
